/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.test {
    export class battleFieldUI extends Scene {
		public sky:Laya.Sprite;
		public grass:Laya.Box;
		public group:Laya.Box;
		public bulletin:Laya.Sprite;
		public player:Laya.Sprite;
		public playerOutLint:ui.test.outLineEffectUI;
		public overGame:Laya.Label;
		public nextLevel:Laya.Label;
		public deTip:Laya.Label;
		public returnHome:Laya.Button;
		public ui:Laya.Box;
		public score:Laya.Label;
		public congratulation:Laya.Label;
		public progress:Laya.ProgressBar;
		public tip:Laya.Button;
		public comic:Laya.Image;
		public jixu:Laya.Label;
		public ball:Laya.Animation;
		public goldPanel:Laya.Image;
		public goldGetText:laya.display.Text;
		public leftArrow:Laya.Animation;
		public rightArrow:Laya.Animation;
		public danmuSystem:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/battleField");
        }
    }
    REG("ui.test.battleFieldUI",battleFieldUI);
    export class danmuSystemUI extends Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/danmuSystem");
        }
    }
    REG("ui.test.danmuSystemUI",danmuSystemUI);
    export class MainUiUI extends Scene {
		public title:laya.display.Text;
		public check:Laya.CheckBox;
		public panel:Laya.Image;
		public btnClose:Laya.Button;
		public rule:Laya.Box;
		public shopList:Laya.List;
		public achievement:Laya.Box;
		public achiTitle:laya.display.Text;
		public achiList:Laya.List;
		public rank:Laya.Box;
		public shopContent:Laya.Box;
		public apprence:laya.display.Text;
		public unlock:laya.display.Text;
		public normal:any;
		public manSelect:Laya.Image;
		public crazyMode:any;
		public buyCrezyMode:Laya.Button;
		public buyUnlockNext:Laya.Button;
		public UnlockNext:any;
		public buyStartCg:Laya.Button;
		public StartCg:any;
		public jumpbuy:Laya.Button;
		public jump:any;
		public runbuy:Laya.Button;
		public run:any;
		public rollbuy:Laya.Button;
		public roll:any;
		public skillSelect:Laya.Image;
		public shoptitle:laya.display.Text;
		public hold:laya.display.Text;
		public addT:Laya.Button;
		public getMoneyPanel:Laya.Box;
		public adsLabel:Laya.Label;
		public ys:Laya.Button;
		public ns:Laya.Button;
		public list:Laya.List;
		public detail:any;
		public StartGame:Laya.Button;
		public select:Laya.Button;
		public Start2:Laya.Button;
		public shop:any;
		public alertPanel:Laya.Image;
		public GetText:laya.display.Text;
		public girl:any;
		public player:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/MainUi");
        }
    }
    REG("ui.test.MainUiUI",MainUiUI);
    export class outLineEffectUI extends Scene {
		public ani1:Laya.FrameAnimation;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/outLineEffect");
        }
    }
    REG("ui.test.outLineEffectUI",outLineEffectUI);
}