/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameUI from "./script/GameUI"
import Enemy from "./script/Enemy"
import GameControl from "./script/GameControl"
import ShakeCamera from "./script/ShakeCamera"
import DanmuUI from "./script/DanmuUI"
import MainUI from "./script/MainUI"
import HpSizeUtil from "./script/HpSizeUtil"
import Bullet from "./script/Bullet"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1600;
    static height:number=900;
    static scaleMode:string="fixedwidth";
    static screenMode:string="horizontal";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="test/battleField.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/GameUI.ts",GameUI);
        reg("script/Enemy.ts",Enemy);
        reg("script/GameControl.ts",GameControl);
        reg("script/ShakeCamera.ts",ShakeCamera);
        reg("script/DanmuUI.ts",DanmuUI);
        reg("script/MainUI.ts",MainUI);
        reg("script/HpSizeUtil.ts",HpSizeUtil);
        reg("script/Bullet.ts",Bullet);
    }
}
GameConfig.init();